
- name: Start apache
  ansible.builtin.systemd_service:
    name: apache2 
    state: started
    enabled: true

- name: Restart apache 
  ansible.builtin.systemd_service:
    name: apache2 
    state: restarted

