---
- name: Python Version
  hosts: lab 
  become: true
  gather_facts: true
  
  tasks:
    
    - name: Get Python version 
      ansible.builtin.command: python3 --version 
      register: python_version

    - name: Extract Python version number
      set_fact:
        python_major_version: "{{ python_version.stdout.split()[1].split('.')[0] }}"
        python_minor_version: "{{ python_version.stdout.split()[1].split('.')[1] }}"
    
    - name: Print version 
      ansible.builtin.debug:
        msg: "{{ python_major_version }}.{{ python_minor_version }}"
